//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch_Comments
    {
        public Batch_Comments()
        {
            this.Product_Number_Batch = new HashSet<Product_Number_Batch>();
            this.Product_Number_Batch_History = new HashSet<Product_Number_Batch_History>();
            this.Product_Number_Batch_Trans = new HashSet<Product_Number_Batch_Trans>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Product_Number_Batch> Product_Number_Batch { get; set; }
        public virtual ICollection<Product_Number_Batch_History> Product_Number_Batch_History { get; set; }
        public virtual ICollection<Product_Number_Batch_Trans> Product_Number_Batch_Trans { get; set; }
    }
}
