//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
     
    public partial class Client_Product_Plan
    {
        public int ID { get; set; }
        public int Client_Product_ID { get; set; }
        public int MassPlan { get; set; }
        public int PlannedMonth { get; set; }
        public int PlannedYear { get; set; }
    
        public virtual Client_Products Client_Products { get; set; }
    }
}
