//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departement
    {
        public int Id { get; set; }
        public string Departement1 { get; set; }
        public Nullable<int> dstatus { get; set; }
        public Nullable<System.DateTime> CtrateDate { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
    }
}
