//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inbound_Shipment
    {
        public Inbound_Shipment()
        {
            this.Product_Number_Batch = new HashSet<Product_Number_Batch>();
        }
    
        public long ID { get; set; }
        public int ShippingNumber { get; set; }
        public System.DateTime ShipmentDate { get; set; }
        public int Status_ID { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public Nullable<System.DateTime> AcknowledgeDate { get; set; }
        public bool isLock { get; set; }
        public string LockedBy { get; set; }
        public Nullable<long> MES_RefID { get; set; }
    
        public virtual Inbound_Shipment_Status Inbound_Shipment_Status { get; set; }
        public virtual ICollection<Product_Number_Batch> Product_Number_Batch { get; set; }
    }
}
