//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryPosition
    {
        public long ID { get; set; }
        public int Client_Product_ID { get; set; }
        public string ReportPeriod { get; set; }
        public string Quality { get; set; }
        public Nullable<int> OpenMetalPad { get; set; }
        public Nullable<int> OpenIntransit { get; set; }
        public Nullable<int> OpenPrebill { get; set; }
        public Nullable<int> TransferPerProduct { get; set; }
        public Nullable<int> MonthlyTransfer { get; set; }
        public Nullable<int> DailyTransfer { get; set; }
        public Nullable<int> DailyRejected { get; set; }
        public Nullable<int> MonthlyIntransit { get; set; }
        public Nullable<int> Daily_Sohar_Container { get; set; }
        public Nullable<int> Daily_Sohar_Breakbulk { get; set; }
        public Nullable<int> OtherPort_Container { get; set; }
        public Nullable<int> OtherPort_Breakbulk { get; set; }
        public Nullable<int> RegionalIntransit { get; set; }
        public Nullable<int> TotalIntransit { get; set; }
        public Nullable<int> DailyStockCorrection { get; set; }
        public Nullable<int> MonthlyStockCorrection { get; set; }
        public Nullable<int> DailyShipped { get; set; }
        public Nullable<int> TotalShipped { get; set; }
        public Nullable<int> TotalShippedRgional { get; set; }
        public Nullable<int> MetalPadEnd { get; set; }
        public Nullable<int> TotalInventory { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> day { get; set; }
    
        public virtual Client_Products Client_Products { get; set; }
    }
}
