//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string password { get; set; }
        public string Ip { get; set; }
        public string locationid { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> empid { get; set; }
        public Nullable<int> deptid { get; set; }
        public Nullable<int> lstatus { get; set; }
        public Nullable<System.DateTime> CtrateDate { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
    }
}
