//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outbound_Shipment
    {
        public Outbound_Shipment()
        {
            this.Packing_Batch = new HashSet<Packing_Batch>();
        }
    
        public long ID { get; set; }
        public string Status { get; set; }
        public Nullable<int> SalesOrderNumber { get; set; }
        public Nullable<int> LineItemNumber { get; set; }
        public string Plant { get; set; }
        public string Product { get; set; }
        public string NetWeight { get; set; }
        public string UoM { get; set; }
        public string GrossWeight { get; set; }
        public string Pieces { get; set; }
        public string Bundles { get; set; }
        public string Containers { get; set; }
        public string ColourMarkings { get; set; }
        public string Date { get; set; }
        public string OPMSalesOrderNumber { get; set; }
        public string OPMSalesOrderLine { get; set; }
        public Nullable<bool> sendStatus { get; set; }
        public Nullable<System.DateTime> sendTime { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChanedDate { get; set; }
        public Nullable<bool> enable { get; set; }
        public Nullable<int> Shipment_Status { get; set; }
        public string ShipmentType { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual ICollection<Packing_Batch> Packing_Batch { get; set; }
    }
}
