//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packing_Batch
    {
        public long ID { get; set; }
        public long Packing_Details_ID { get; set; }
        public long Batch_ID { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public int Status_ID { get; set; }
        public Nullable<long> Outbound_Shipment_ID { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Outbound_Shipment Outbound_Shipment { get; set; }
        public virtual Outbound_Status Outbound_Status { get; set; }
        public virtual Packing_Details Packing_Details { get; set; }
        public virtual Product_Number_Batch Product_Number_Batch { get; set; }
    }
}
