//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packing_Type
    {
        public Packing_Type()
        {
            this.Packing_Details = new HashSet<Packing_Details>();
        }
    
        public int ID { get; set; }
        public string PackingType { get; set; }
        public string SAPCode { get; set; }
    
        public virtual ICollection<Packing_Details> Packing_Details { get; set; }
    }
}
