//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packing_Details
    {
        public Packing_Details()
        {
            this.Packing_Batch = new HashSet<Packing_Batch>();
        }
    
        public long ID { get; set; }
        public string PackingName { get; set; }
        public string data1 { get; set; }
        public string data2 { get; set; }
        public string data3 { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public long SalesOrder_Line_ID { get; set; }
        public int Packing_Type_ID { get; set; }
        public bool isLock { get; set; }
        public bool isRelease { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual ICollection<Packing_Batch> Packing_Batch { get; set; }
        public virtual Packing_Type Packing_Type { get; set; }
        public virtual SalesOrder_Line SalesOrder_Line { get; set; }
    }
}
