//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Number_Analysis
    {
        public long ID { get; set; }
        public Nullable<long> Product_Number_ID { get; set; }
        public string AnalysisName { get; set; }
        public Nullable<double> AnalysisValue { get; set; }
    
        public virtual Product_Number Product_Number { get; set; }
    }
}
