//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Number_Batch_History
    {
        public long ID { get; set; }
        public long Batch_ID { get; set; }
        public long Product_Number_ID { get; set; }
        public int BatchNumber { get; set; }
        public int Mass { get; set; }
        public int Status_ID { get; set; }
        public long Inbound_Shipment_ID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> Batch_Comment_ID { get; set; }
    
        public virtual Batch_Comments Batch_Comments { get; set; }
        public virtual Product_Number_Batch Product_Number_Batch { get; set; }
        public virtual Product_Number_Batch_Status Product_Number_Batch_Status { get; set; }
    }
}
