//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Number_Batch_Location
    {
        public Product_Number_Batch_Location()
        {
            this.Product_Number_Batch = new HashSet<Product_Number_Batch>();
        }
    
        public int ID { get; set; }
        public string Location_Name { get; set; }
        public Nullable<int> Client_Product_ID { get; set; }
        public bool Enabled { get; set; }
        public Nullable<bool> isAllowed { get; set; }
    
        public virtual ICollection<Product_Number_Batch> Product_Number_Batch { get; set; }
    }
}
