//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Quality
    {
        public Product_Quality()
        {
            this.Product_Number = new HashSet<Product_Number>();
        }
    
        public int ID { get; set; }
        public string QualityName { get; set; }
        public string QualityCode { get; set; }
    
        public virtual ICollection<Product_Number> Product_Number { get; set; }
    }
}
