//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Number
    {
        public Product_Number()
        {
            this.Product_Number_Analysis = new HashSet<Product_Number_Analysis>();
            this.Product_Number_Batch = new HashSet<Product_Number_Batch>();
        }
    
        public long ID { get; set; }
        public int Client_Product_ID { get; set; }
        public int Quality_ID { get; set; }
        public int Product_Status_ID { get; set; }
        public string ProductNumber { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public string LockedReason { get; set; }
        public string LockedBy { get; set; }
        public Nullable<long> MES_RefID { get; set; }
    
        public virtual Client_Products Client_Products { get; set; }
        public virtual ICollection<Product_Number_Analysis> Product_Number_Analysis { get; set; }
        public virtual ICollection<Product_Number_Batch> Product_Number_Batch { get; set; }
        public virtual Product_Quality Product_Quality { get; set; }
        public virtual Product_Status Product_Status { get; set; }
    }
}
