//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder_Line
    {
        public SalesOrder_Line()
        {
            this.Packing_Details = new HashSet<Packing_Details>();
        }
    
        public long ID { get; set; }
        public long SalesOrder_ID { get; set; }
        public string OrderLineAction { get; set; }
        public Nullable<int> OrderLineNo { get; set; }
        public Nullable<bool> LineActionStatus { get; set; }
        public string FOBCode { get; set; }
        public string FOBName { get; set; }
        public string CustPONo { get; set; }
        public double OrderedQuantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<System.DateTime> SchedShipDate { get; set; }
        public Nullable<int> NumberOfContainer { get; set; }
        public Nullable<int> NumberOfBundles { get; set; }
        public string TransportationModeCode { get; set; }
        public string TransportationModeDesc { get; set; }
        public string AlcanItemNo { get; set; }
        public string CommonItemNo { get; set; }
        public string AlloySource { get; set; }
        public string AlloyNo { get; set; }
        public string VesselName { get; set; }
        public string VoyageNumber { get; set; }
        public Nullable<System.DateTime> ScheduledSailingDate { get; set; }
        public string LoadPort { get; set; }
        public string DestinationPort { get; set; }
        public string BookingNo { get; set; }
        public string ShippingLine { get; set; }
        public string ShipTolMax { get; set; }
        public string ShipTolMin { get; set; }
        public Nullable<bool> enable { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<Packing_Details> Packing_Details { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
