//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder_Customer
    {
        public long ID { get; set; }
        public long SalesOrder_ID { get; set; }
        public string relationShip { get; set; }
        public string Customer_No { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Address1 { get; set; }
        public string Customer_Address2 { get; set; }
        public string Customer_Address3 { get; set; }
        public string Customer_City { get; set; }
        public string Customer_CountryCode { get; set; }
        public string Customer_CountryName { get; set; }
        public string Customer_PostalCode { get; set; }
        public Nullable<bool> enable { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
    
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
