//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagmeent
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public SalesOrder()
        {
            this.SalesOrder_Customer = new HashSet<SalesOrder_Customer>();
            this.SalesOrder_Line = new HashSet<SalesOrder_Line>();
        }
    
        public long ID { get; set; }
        public int Cleint_ID { get; set; }
        public string OrderAction { get; set; }
        public bool OrderActionStatus { get; set; }
        public int OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderRefNum { get; set; }
        public string CurrencyCode { get; set; }
        public string PaymentTermCode { get; set; }
        public string PaymentTermDesc { get; set; }
        public Nullable<bool> enable { get; set; }
        public Nullable<System.DateTime> RecordUpdated { get; set; }
        public Nullable<System.DateTime> fileReceivedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> OrderStatus { get; set; }
    
        public virtual ICollection<SalesOrder_Customer> SalesOrder_Customer { get; set; }
        public virtual ICollection<SalesOrder_Line> SalesOrder_Line { get; set; }
        public virtual SAMY_Client SAMY_Client { get; set; }
    }
}
